:experimental:

= Route to your Revisioned Serverless Service

The sample code in this section helps you to deploy serverless workload using https://github.com/knative/docs/tree/master/serving[Knative-Serving] following configuration and route workflow.  The code also shows how to distribute the traffic across multiple revisions of a serverless workload.

This repo folder has NodeJS example.



== Prerequisites

- Basic knowledge of how to build container images with https://buildah.io[buildah]

=== User namespaces
By default RHEL/Centos sets the max_user_namespaces value to **0**, you need to set that to bigger value to make the buildah container builds to pass, set the `max_user_namespaces` kernel parameter to 15000. For more details on user namespaces refer to http://man7.org/linux/man-pages/man7/user_namespaces.7.html

[source,bash]
----
minishift ssh
sudo -i
echo "sysctl user.max_user_namespaces=15000" >> /etc/sysctl.d/99-sysctl.conf
sysctl -p
----
save the value permanently surviving reboots

=== Skipping tag to digest
The Knative-serving is by default skips tag to digest for the registries `ko.local` and `dev.local`, as part of this demo you will push the build image to internal default docker registry (__docker-registry.default.svc:5000__) , you will need update `registriesSkippingTagResolving` attribute of the config-controller ConfigMap to include the registry **docker-registry.default.svc:5000** to be skipped for tag to digest resolving.

[source,bash]
----
val=$(oc -n knative-serving get cm config-controller -oyaml | yq r - data.registriesSkippingTagResolving | awk '{print $1",docker-registry.default.svc:5000"}')
oc -n knative-serving get cm config-controller -oyaml | yq w - data.registriesSkippingTagResolving $val | oc apply -f -
----


== Building and Deploying Application

The source folder **demo** will be referred as `$PROJECT_HOME`. The following section details on how to build NodeJS Application.

=== Building 

The application uses Knative-build with Buildah invoking it through a Knative BuildTemplate

=== Node


=== Apply BuildTemplate

[source,bash]
----
cd $PROJECT_HOME

oc apply -f build/templates/node-buildah-template.yaml

----

=== Deploying Service

==== Revision 1

[source,bash]
----
cd $PROJECT_HOME
oc apply -f config/configuration_rev1.yaml
oc apply -f route/route_default.yaml
----

Update the environment variable `MESSAGE_PREFIX` in link:./config/configuration_rev2.yaml[configuration_rev2.yaml]

==== Revision 2

[source,bash]
----
cd $PROJECT_HOME
oc apply -f config/configuration_rev2.yaml
----

=== Invoking Service

[source,bash]
----
bin/call.sh
----

=== Split traffic by revisions

==== 50-50

[source,bash]
----
cd $PROJECT_HOME
oc apply -f route/route_rev1-50_rev2-50.yaml
----

==== All traffic to Revision 2

[source,bash]
----
cd $PROJECT_HOME
oc apply -f route/route_all_rev2.yaml
----

==== All traffic to Revision 1

[source,bash]
----
cd $PROJECT_HOME
oc apply -f route/route_all_rev1.yaml
----

== Useful commands

The following are some useful commands

- Get all **Knative services** on project **myproject** `oc -nmyproject get service.serving.knative.dev`
- Get all **Knative configurations** on project **myproject** `oc -nmyproject get configuration.serving.knative.dev`
- Get all **Knative routes** on project **myproject** `oc -nmyproject get route.serving.knative.dev`
- Get all **Knative revisions** on project **myproject** `oc -nmyproject get revision.serving.knative.dev`

[TIP]
====
If you need to get the specific service,configuration,route or revision etc., the add the name to the end of the commands above
e.g to get our service named **greeter**:

`oc -n myproject get service.serving.knative.dev greeter`
====
