apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: greeter
spec:
  revisionTemplate:
    metadata:
      labels:
        app: greeter
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
    spec:
      container:
        # This should be a fully qualified domain name e.g. quay.io/example/myimage:mytag
        # This is configured to use the inbuilt default docker registry
        image: docker-registry.default.svc:5000/myproject/greeter:0.0.1
        env:
          - name: MESSAGE_PREFIX
            value: Ciao
